name: Fetch GitHub Trending

on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: '0 1 * * *' # UTC 凌晨 1 点
    - cron: '0 7 * * *' # UTC 早 7 点
    - cron: '0 13 * * *' # UTC 中午 1 点
    - cron: '0 19 * * *' # UTC 下午 7 点

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      # - name: Build the languages
      #   run: pnpm gen:lang

      - name: Build the trending
        run: pnpm build

      - name: Commit and Push changes
        if: github.event_name == 'schedule' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          COMMIT_TIME=$(date +'%Y-%m-%d %H:%M:%S')
          git commit -m "publish🚀: Fetch GitHub Trending at $COMMIT_TIME"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}